# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FilterLayers
                                 A QGIS plugin
 Un plugin qui permet de filtrer les couches de votre projet FTTH
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-09
        copyright            : (C) 2020 by Simon Ducournau
        email                : simon.ducournau@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FilterLayers class from file FilterLayers.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .filter_layers import FilterLayers
    return FilterLayers(iface)
