#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Script to fix QGIS widget imports in pyuic5-generated files.

When pyuic5 compiles a .ui file with promoted QGIS widgets, it generates
incorrect import statements like:
    from qgscheckablecombobox import QgsCheckableComboBox
    
This script replaces them with the correct imports:
    from qgis.gui import QgsCheckableComboBox

Usage:
    python fix_ui_imports.py <filename.py>
"""

import re
import sys


# Mapping of incorrect module names to correct import statements
QGIS_WIDGETS = {
    'qgscheckablecombobox': 'QgsCheckableComboBox',
    'qgscollapsiblegroupbox': 'QgsCollapsibleGroupBox',
    'qgsdoublespinbox': 'QgsDoubleSpinBox',
    'qgsfeaturepickerwidget': 'QgsFeaturePickerWidget',
    'qgsfieldexpressionwidget': 'QgsFieldExpressionWidget',
    'qgsmaplayercombobox': 'QgsMapLayerComboBox',
    'qgsprojectionselectionwidget': 'QgsProjectionSelectionWidget',
    'qgspropertyoverridebutton': 'QgsPropertyOverrideButton',
    'qgsfieldcombobox': 'QgsFieldComboBox',
    'qgsfilterlineedit': 'QgsFilterLineEdit',
    'qgsspinbox': 'QgsSpinBox',
}


def fix_imports(content: str) -> str:
    """
    Fix QGIS widget imports in pyuic5-generated Python code.
    
    Args:
        content: Original file content
        
    Returns:
        Fixed file content
    """
    # Track which widgets were found
    found_widgets = []
    
    # Find all incorrect imports and remove them
    for module_name, widget_class in QGIS_WIDGETS.items():
        pattern = rf'^from {module_name} import {widget_class}\s*$'
        if re.search(pattern, content, re.MULTILINE):
            found_widgets.append(widget_class)
            # Remove the incorrect import line
            content = re.sub(pattern + r'\n?', '', content, flags=re.MULTILINE)
    
    # If we found any widgets, add the correct imports after PyQt5 imports
    if found_widgets:
        # Build the correct import statement
        if len(found_widgets) == 1:
            qgis_import = f"from qgis.gui import {found_widgets[0]}\n"
        else:
            widgets_str = ',\n    '.join(sorted(found_widgets))
            qgis_import = f"# Import QGIS widgets\nfrom qgis.gui import (\n    {widgets_str}\n)\n"
        
        # Find the location after PyQt5 imports
        pyqt_import_pattern = r'(from PyQt5 import QtCore, QtGui, QtWidgets\s*\n)'
        match = re.search(pyqt_import_pattern, content)
        
        if match:
            # Insert after PyQt5 imports
            insert_pos = match.end()
            content = content[:insert_pos] + '\n' + qgis_import + '\n' + content[insert_pos:]
        else:
            # Fallback: insert after encoding declaration
            content = content.replace(
                '# run again.  Do not edit this file unless you know what you are doing.\n\n\n',
                f'# run again.  Do not edit this file unless you know what you are doing.\n\n\n{qgis_import}\n'
            )
        
        print(f"Fixed imports for: {', '.join(found_widgets)}")
    else:
        print("No QGIS widget imports found to fix.")
    
    return content


def main():
    if len(sys.argv) < 2:
        print("Usage: python fix_ui_imports.py <filename.py>")
        sys.exit(1)
    
    filename = sys.argv[1]
    
    try:
        with open(filename, 'r', encoding='utf-8') as f:
            content = f.read()
        
        fixed_content = fix_imports(content)
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(fixed_content)
        
        print(f"Successfully processed: {filename}")
        sys.exit(0)
        
    except FileNotFoundError:
        print(f"Error: File not found: {filename}")
        sys.exit(1)
    except Exception as e:
        print(f"Error processing file: {e}")
        sys.exit(1)


if __name__ == '__main__':
    main()
